project:
  type: website

execute:
  warning: false
  message: false
  exclude:
    - Hands-on_Ex/Hands-on_Ex03/Part_02/Hands-on_Ex03-2.qmd

website:
  title: "ISSS608"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exercise 0"
          href: "Hands-on_Ex/Hands-on_Ex00/Hands-on_Ex00.html"
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "Hands-on Exercise 8"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "Hands-on Exercise 9"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
        - text: "Hands-on Exercise 10"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
          
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 1"
          href: "https://public.tableau.com/app/profile/fook.ming.ee/viz/In-classEx01_17377902282300/Dashboard1"
        - text: "In-class Exercise 2"
          href: "https://public.tableau.com/app/profile/fook.ming.ee/viz/In-classEx02_17377901895230/Dashboard2"
        - text: "In-class Exercise 3"
          href: "https://public.tableau.com/app/profile/fook.ming.ee/viz/In-classEx03-MyFirstStory/Story1"
        - text: "In-class Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In-class Exercise 5"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
        - text: "In-class Exercise 5 - Tableau Heatmap 1"
          href: "https://public.tableau.com/app/profile/fook.ming.ee/viz/In-class_Ex05_Tableau_21/Sheet1"
        - text: "In-class Exercise 5 - Tableau Heatmap 2"
          href: "https://public.tableau.com/app/profile/fook.ming.ee/viz/In-class_Ex05_Tableau_22/Sheet2"
        - text: "In-class Exercise 6"
          href:  "https://isss608eefm.shinyapps.io/In-class_Ex06/"
        - text: "In-class Exercise 7"
          href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
        - text: "In-class Exercise 8 - Tableau Map-1"
          href: "https://public.tableau.com/app/profile/fook.ming.ee/viz/In-class_Ex08_1_17420459719190/SingaporePool"
        - text: "In-class Exercose 8 - Tableau Map-2"
          href: "https://public.tableau.com/app/profile/fook.ming.ee/viz/In-class_Ex08_2_17420215082800/SingaporePropertyProjectType2018"

    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"

#          menu:
#            - text: "Part 1: Programming Interactive Data Visualisation with R"
#              href: "Hands-on_Ex/Hands-on_Ex03/Part_1/Part1.html"
#            - text: "Part 2: Programming Animated Statistical Graphics with R"
#              href: "Hands-on_Ex/Hands-on_Ex03/Part_2/Part2.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd
      

# Define the sidebar:
#  sidebar:
#    style: "floating"    # "floating" or "classic"
#    search: true         # Adds a search box in the sidebar
#    contents:
#      - "index.qmd"
#      - "about.qmd"
#      - section: "Guides"
#        contents:
#          - "guide1.qmd"
#          - "guide2.qmd"
#      - section: "References"
#        contents:
#          - "reference1.qmd"
#          - "reference2.qmd"
# End of sidebar
      
format:
  html:
    theme: 
      - Cosmo
    css: styles.css
    number-sections: true
    toc: true
    tabset: true

editor: visual
